services:
  db:
    image: postgres:latest
    restart: always
    shm_size: 128mb
    environment:
      POSTGRES_PASSWORD: aGoodPassword
      POSTGRES_USER: admin
    networks:
      my_network:
        ipv4_address: 172.20.0.2
    hostname: my_postgres_db
    ports:
      - 5432:5432

networks:
  my_network:
    driver: bridge
    ipam:
      config:
        - subnet: 172.20.0.0/16